'use client';
import { FormEvent, useEffect, useState } from 'react';

type Message={role:'user'|'assistant';content:string;provider?:string};
export default function Home(){const[input,setInput]=useState(''),[messages,setMessages]=useState<Message[]>([]),[busy,setBusy]=useState(false),[speaking,setSpeaking]=useState(false),[health,setHealth]=useState<any>(null);
useEffect(()=>{fetch('/api/chat').then(r=>r.json()).then(setHealth).catch(()=>null)},[]);
function speak(t:string){if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='pl-PL';u.rate=.92;u.pitch=1.08;u.onstart=()=>setSpeaking(true);u.onend=()=>setSpeaking(false);window.speechSynthesis.speak(u)}
async function send(e:FormEvent){e.preventDefault();const text=input.trim();if(!text||busy)return;setInput('');const next=[...messages,{role:'user' as const,content:text}];setMessages(next);setBusy(true);try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,history:messages})});const d=await r.json();const reply=d.text||d.error||'Nie mam jeszcze odpowiedzi.';setMessages([...next,{role:'assistant',content:reply,provider:d.provider}]);speak(reply)}catch{setMessages([...next,{role:'assistant',content:'Nie udało się połączyć z agentem.'}])}finally{setBusy(false)}}
return <div className="shell"><header className="top"><div className="brand"><span className="orb"/>Bebok AI</div><span className="status">● {health?.providers?.ollama?'OLLAMA':health?.providers?.openrouter?'OPENROUTER':'DEMO'}</span></header><main className="main"><section className="hero"><div className={'avatarWrap '+(speaking?'speaking':'')}><img src="/bebok-character.svg" alt="Bebok AI"/><span className="pulse"/></div><div className="eyebrow">AI AGENT · INTERACTIVE BEBOK</div><h1>Twój własny<br/><em>Bebok AI.</em></h1><p>{speaking?'Bebok właśnie do Ciebie mówi…':'Napisz do mnie. Odpowiem głosem i zapamiętam kontekst rozmowy.'}</p><div className="features"><span className="pill">✓ Agent</span><span className="pill">✓ Głos PL</span><span className="pill">→ Pamięć</span><span className="pill">→ Video</span></div></section><section className="chat"><div className="chatHead"><div><strong>Bebok</strong><small>Twój interaktywny agent AI</small></div><span className="live">LIVE</span></div><div className="messages">{messages.length===0?<div className="empty"><div className="emptyIcon">✦</div><strong>Hej! Jestem Bebok.</strong><span>Napisz „Cześć Bebok!” i usłyszysz odpowiedź.</span></div>:messages.map((m,i)=><div key={i} className={m.role==='user'?'bubbleRow user':'bubbleRow'}><div className="bubble"><div>{m.content}</div>{m.provider&&<small>{m.provider}</small>}</div></div>)}</div><form className="composer" onSubmit={send}><input value={input} onChange={e=>setInput(e.target.value)} placeholder={busy?'Bebok myśli…':'Napisz do Beboka…'} disabled={busy}/><button disabled={busy}>{busy?'…':'Wyślij →'}</button></form></section><div className="footer">Bebok AI · agent + voice · klucze poza repo</div></main></div>}
